### ISSUE TITLE
Adjust footer text to reflect Australian network

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#11]
(via Craig)

**Comment by equivalentideas** [comment]
This text is edited in the WordPress Widgets admin area https://opengovernment.org.au/wp-admin/widgets.php

**Comment by equivalentideas** [comment]
I've done a simple replacement of the UK stuff with our current 'introduction to the AOGPN' text and replaced their link to the forum with a link to our mail list:

![screen shot 2016-01-25 at 5 14 42 pm](https://cloud.githubusercontent.com/assets/1239550/12543777/262b46f4-c387-11e5-98e7-bf7cc8f9886d.png)

This section seems very similar in purpose to the homepage introduction section to me: To give people who have come to any page on the site (a news update or event via twitter for example) some quick context about what the network is and does and give them a next step to get involved. I'm going to suggest we wrap the improvement of the text in the section with the issue about improving the homepage intro text #36 .

I'm going to close this issue since this text now reflects the Australian network, please open new issues to improve it ;-)
