### ISSUE TITLE
text and new heading for UK Open Gov Section equivalent

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#16]
(via Craig) Homepage:

NEED: Text & new heading for the current 'UK Open Gov' section (drawn from Peter's doc?)

**Comment by equivalentideas** [comment]
This is on the [homepage](http://www.opengovernment.org.uk/) under the heading “Activity around the UK”.

> ### UK Open Gov
> 
> The UK Open Government Network collaborates with and challenges governments in the UK to develop and implement ambitious open government reforms through the UK’s membership of the Open Government Partnership.
> 
> Read more

![screen shot 2016-01-19 at 11 18 17 am copy](https://cloud.githubusercontent.com/assets/1239550/12411209/ae55459a-bed0-11e5-9ed1-415b3f3ca78c.png)

Can I suggest a title that is a engaging, few-word summary of what the network does, since we already have the organisation name as the page title here.

**Comment by equivalentideas** [comment]
Here's a pass at this, boiling down the _Introduction_ and _Purpose_ sections of the Australian Open Government Partnership Network Terms and Reference. Because the name of the organisation is big and clear in the page title, I think something more engaging and summarising what we're about (or even better: what we do) would be good for the title of this section.

> ### For better, more open government
> 
> We are a coalition individuals and organisations committed to making
> government work better through transparency, open government, public
> participation, deliberation and accountability. We’re collaborating with and
> keeping-an-eye-on the Australian Government through the Open Government
> Partnership process–making sure it leads to ambitious reforms.
> 
> **Read more**

**Comment by equivalentideas** [comment]
I'm going to put this back into the backlog for now until @kat is back and we can go from there with developing this.

**Comment by kat** [comment]
@equivalentideas sounds good to me - am adding another issue to add the Terms of Reference too...

**Comment by craigthomler** [comment]
Hi equivalentideas,

Not a bad try, though a little too adversarial for the goals of the network. You can use the text below:

The Australian Open Government Partnership Network (AOGPN) is a network of individals and organisations committed to helping governments work better by promoting transparency, open government, public participation, deliberation and accountability. Formed following the Australian Government's decision to join the Open Government Partnership (OGP), we support this goal through information-sharing and working cooperatively to help government set and meet ambitious and achievable open government reforms.

**Comment by equivalentideas** [comment]
Thanks @craigthomler I've added and deployed that with a couple of small tweaks.
- Used "We" instead of the full org name because it's just above in the header, and it's more conversational with 'we'.
- Removed the 'OGP' abbreviation because we don't mention it again in this bit of text.

![screen shot 2016-01-25 at 4 22 50 pm](https://cloud.githubusercontent.com/assets/1239550/12543155/83080bde-c380-11e5-8336-900fc0b5ebfb.png)

I'm gonna open a new issue to work through other specific changes since this issue was primarily about just adapting the text for the Australian Open Government Partnership Network and that's done. Close this one :rocket:
