### ISSUE TITLE
Remove “Activity around the UK” tabs module on home page

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#4]
The top of the current homepage has a tabbed module with information about the different UK groups and what they are up to:

![screen shot 2016-01-19 at 11 18 17 am](https://cloud.githubusercontent.com/assets/1239550/12406124/60b7d442-be9e-11e5-8817-316550b512a9.png)

In context:

![screen shot 2016-01-19 at 11 17 01 am](https://cloud.githubusercontent.com/assets/1239550/12406259/7f11585e-be9f-11e5-96c5-bcb3aaf701e2.png)

In the Australia version we don't have these country categorisation of posts (see #2).

We could replace the countries tabs module with a similar module without tabs. This could include a short statement about the Australian Open Government Partnership Network and the latest posts. This would help people understand the aims of the network asap.

This would also mean we could remove the “Latest updates” section on the homepage, which in our case would be a duplicate of the content in the “Latest posts” section. This would simplify it quite a bit and making the Events section more prominent.

![img_4395](https://cloud.githubusercontent.com/assets/1239550/12406376/737f5d78-bea0-11e5-8526-4f7b32af9fc8.jpg)

For the 'About us' section in those sketches I'd suggest something more like “What we do” or a few word summary of the aims as the heading instead of 'About us'.

**Comment by equivalentideas** [comment]
> For the 'About us' section in those sketches I'd suggest something more like “What we do” or a few word summary of the aims as the heading instead of 'About us'.

The content for this section is covered in https://github.com/AOGPN/opengovernment.org.au/issues/16

**Comment by equivalentideas** [comment]
Here's a quick code version of the sketch above:

![screen shot 2016-01-22 at 2 39 10 pm](https://cloud.githubusercontent.com/assets/1239550/12501886/bfc7d034-c116-11e5-98de-13f3a64fd6bd.png)

For me that’s not really working. The summary/about text area on the left feels repetitive with the tagline to the right of the header. The stripped back latest posts on the right is doing no where near as good a job of grabbing my attention and giving context as the more filled out version further down the page.

Here's another idea where we bring the latest posts and tweets section up from further down the page. That way it becomes all about the latest thing thats going on and discussion people can get involved with. If they need to learn about what the network does there's the tagline in the header and also the about page with lots of info.

![screen shot 2016-01-22 at 2 44 32 pm](https://cloud.githubusercontent.com/assets/1239550/12501934/4aff6e00-c117-11e5-9580-f3da1b72054f.png)

Could you give me some feedback on this @henare ?

**Comment by henare** [comment]
> For me that’s not really working. The summary/about text area on the left feels repetitive with the tagline to the right of the header. The stripped back latest posts on the right is doing no where near as good a job of grabbing my attention and giving context as the more filled out version further down the page.

I think your reaction to that is really interesting and it's great you're thinking about this. I'll come back to this after responding to the next paragraph.

> Here's another idea where we bring the latest posts and tweets section up from further down the page. That way it becomes all about the latest thing thats going on and discussion people can get involved with. If they need to learn about what the network does there's the tagline in the header and also the about page with lots of info.

That's sounds like designing for the imaginary model citizen that comes to the front page and immediately wants to get involved. The much more likely scenario is that someone comes to the home page either wanting to find out what this is all about or hits the home page but wants to quickly go to some other specific page.

So we should probably design around the concept of very quickly being able to get a sense of what the AOGPN is and very quickly being able to find and access other parts of the site.

---

At this stage we're supposed to be just using what the UK has and not doing redesign. The first version is closer to that approach and I think we can address your issues with it while also doing the nice thing you were after with the second version.

> The summary/about text area on the left feels repetitive with the tagline to the right of the header.

Good call. We can get rid of most of that repetition by tweaking the text, e.g. "we" instead of "Australian Open Government Partnership Network", and by putting more meaty, new, and useful detail here.

I'm less sure what that last point means but we need to think about it from the perspective of someone that doesn't know what this is all about.

> The stripped back latest posts on the right is doing no where near as good a job of grabbing my attention and giving context as the more filled out version further down the page.

How about instead of News we have ways people can get involved. So the idea would be to give people enough information in the new, meaty summary section that they're informed and excited enough to want to get involved?

**Comment by equivalentideas** [comment]
Thanks @henare that's great.

> At this stage we're supposed to be just using what the UK has and not doing redesign. The first version is closer to that approach and I think we can address your issues with it while also doing the nice thing you were after with the second version.

That sounds really good :+1: Is this really about making #16 awesome? We could implement it and then iterate that text with new issues.

> How about instead of News we have ways people can get involved.

I think that's a great idea. What are some ways people could get involved? ping @kat

**Comment by henare** [comment]
> Is this really about making #16 awesome?

Yep, looks like it.

So that new people coming to the site actually understand what AOGPN is we need to make sure it's not just about the AOGPN values but also who we actually are and what we actually do. So often I find myself reading things like about pages and still having no freaking clue what the organisation is or does :smiley:

**Comment by equivalentideas** [comment]
> what we actually do

:star2: :star: :star2: :star: :star2:

**Comment by equivalentideas** [comment]
To keep this moving I'm going to implement the simple version above and then raise issues for making the text more useful and changing the posts list over for ways people can get involved for those discussions.

**Comment by equivalentideas** [comment]
I've implemented the simple example we like from above and deployed:

![screen shot 2016-01-25 at 4 22 50 pm](https://cloud.githubusercontent.com/assets/1239550/12543106/05882ed2-c380-11e5-8b3d-0348a0e3a4a6.png)

See:
7806336 Add about text with simple latest posts feed to top of homepage
02209a1 Make module id more accurate for current purpose
57ecc97 Increase the size of the introduction text
d6c4c77 Reduce spacing under intro heading
2f1f711 Increase spacing around 'read more' link so it stands out more
6288e92 Update the href of the 'read more' link to something real
b565565 Increase number of posts shown since we have the extra space
20e9b73 Use 'We' instead of full name since it’s just above in the header
db753ef OGP isn't mentioned again here so there's no need to provide abbreviation

**Comment by equivalentideas** [comment]
I've extracted the changes we want to make into #36 and #37 for development. I'll close this issue now as we've removed the 'Activity around the UK' tabs and replaced them with a something basic for our context.
