### ISSUE TITLE
Create a membership form to send around the network

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#59]
There are many people in the google group who have not confirmed their agreement with the terms of ref. One way to get them to take action is to send around a form with:
- tick to confirm your agreement with the terms of ref
- assign yourself to a working group
- at the end of the month you'll be unsubscribed from the list unless you do something

**Comment by equivalentideas** [comment]
@henare suggests we also tell non-menbers they can sign up to the Code for Australia OGP announcements list for basic info about events etc.

**Comment by kat** [comment]
when we ask people to assign themselves to a working group what will that mean in practise?

**Comment by kat** [comment]
Initial suggestion for form via (Peter Timmins)

" Membership"

Name.............

I hereby join the Australian Open Government Partnership Network in my

Individual capacity

As representative of............. (organisation)

The  goals of the organisation are to work towards public (rather than private or commercial) interests and are compatible with AOGPN principles.

In joining the Network I

```
* Endorse the Open Government Declaration (see Annex A Terms of Reference.)

* Agree to abide by the Network’s principles:

* To act in and for the public interest, not for private or commercial purposes.
```

To take any decisions required impartially, fairly and on merit, using the best evidence and without discrimination or bias, acting in an open and transparent manner. Information should not be withheld from the public unless there are clear reasons for so doing.

```
Be accountable for decisions and actions.

Promote and support these principles.

Have no conflicts of interest. I am not:
```

●      a government minister or shadow minister

●      a political advisor working with government ministers or shadow ministers

●      a government official working on open government policy

●      a corporate lobbyist (e.g. an individual lobbying for a private interest, potentially in conflict with the Open Government Declaration or AOGPN principles.)

**Comment by kat** [comment]
pending response from Craig regarding his newly created google group, if that's intended for this network's discussion. He's created some threads on there related to the international working groups that Toby referred to as a starting point for discussion also. ie. 

```
Fiscal Openness,
Legislative Openness,
Access to Information,
Open Data and
Openness in Natural Resources
```

**Comment by equivalentideas** [comment]
Working on the form in Google Docs https://docs.google.com/a/oaf.org.au/forms/d/1Rwq8cLkSUQBRVin33QmMc2xwsgeA91DP_i5u3dLYIoA/edit?uiv=1

**Comment by craigthomler** [comment]
Hi Kat,

Actually the groups I created were based on Peter Timmin's defined working groups that have been discussed by the steering committee.

Cheers,

Craig

**Comment by kat** [comment]
I think you'll find @craigthomler that these were a suggestion Peter thew in the ring, and no-one piped up at the time. Having considered them we came up with a couple of extras. Are you going to answer the question or not?

**Comment by craigthomler** [comment]
I'm confused - I did answer your question.

---

Craig Thomler

http://egovau.blogspot.com
http://twitter.com/CraigThomler
http://au.linkedin.com/in/craigthomler
http://www.slideshare.net/CraigThomler
http://www.slideshare.net/CraigThomler%20

_Mobile:_ 0411 780 194 (_International:_ +61 411 780 194)
_Phone:_ 02 6161 4508 (_International: *+61 2 6161 4508)
*Skype:_ craig.thomler

**Comment by kat** [comment]
So is the email group you created just for the steering committee, for Network members only or for everyone? That's the question I'm asking, and I haven't seen an answer here. Perhaps you could repeat the answer for me?

**Comment by kat** [comment]
ok @craigthomler now I see you've answered here, that you've answered me in the email thread! Got it!

**Comment by kat** [comment]
Confirming the flow here:
write to non members who are currently part of the OGPAustraliaNetwork google group
ask them to confirm agreement with the terms of ref and give information/see if there's a working group they're interested in connecting with
- directly add them to a new google group that's only for members. Tell them that they'll be receiving a confirmation from the new google group

**Comment by equivalentideas** [comment]
First version of this form is done https://docs.google.com/a/oaf.org.au/forms/d/1Rwq8cLkSUQBRVin33QmMc2xwsgeA91DP_i5u3dLYIoA/formResponse

Closing this issue and we'll make new ones for where to link to it. There's already an issue to send this to all the people on the Google Group #76

**Comment by craigthomler** [comment]
I responded to the email you sent to the steering committee. I've included
my response below, although I see you've already responded to the steering
committee discussion as well.

Hi Kat,

The group was for discussion across network members to collect and refine
ideas - as you'll see from the text the group.

Having people explicitly pledge to the Network's code or be expelled wasn't
part of my thinking. I thought we were an inclusive network for people
supportive of open government goals. I wasn't expecting to have to select
out people who felt otherwise, they simply won't join.

Cheers,

Craig

---

Craig Thomler

http://egovau.blogspot.com
http://twitter.com/CraigThomler
http://au.linkedin.com/in/craigthomler
http://www.slideshare.net/CraigThomler
http://www.slideshare.net/CraigThomler%20

_Mobile:_ 0411 780 194 (_International:_ +61 411 780 194)
_Phone:_ 02 6161 4508 (_International: *+61 2 6161 4508)
*Skype:_ craig.thomler

**Comment by craigthomler** [comment]
Hi Luke,

It would be a good idea to allow people to select more than one working
group to join. There's people with useful contributions across topics.
Effectively this would mean checkboxes rather than radio buttons for the
question 'Which of our working groups do you want to work with? '

I can see a practical case for limiting people to X number of working
groups (X being 3 or 4) - but that's something to discuss with the Steering
Committee.

I note you've used different language to Peter for the different groups -
ie Civic Participation rather than Citizen Engagement. Why is that the
case?

I find the 'you must agree to these terms' unnecessarily confronting. I'll
discuss with the Steering Committee & if the Committee is strongly
committed to the pledge approach, will craft some more inclusive and
inviting language.

When saying Yes it pushes the user to a Submission form. It's an
unnecessary step from a user experience perspective. Unless there's a
technical requirement to keep it, can it be dropped, with the prior
agreement serving as the submission..

Thanks,

Craig

---

Craig Thomler

http://egovau.blogspot.com
http://twitter.com/CraigThomler
http://au.linkedin.com/in/craigthomler
http://www.slideshare.net/CraigThomler
http://www.slideshare.net/CraigThomler%20

_Mobile:_ 0411 780 194 (_International:_ +61 411 780 194)
_Phone:_ 02 6161 4508 (_International: *+61 2 6161 4508)
*Skype:_ craig.thomler

**Comment by equivalentideas** [comment]
Hey Craig thanks for that. Here's the current form: https://docs.google.com/forms/d/1Rwq8cLkSUQBRVin33QmMc2xwsgeA91DP_i5u3dLYIoA/viewform

Let's open new issues for specific changes (like https://github.com/AOGPN/opengovernment.org.au/issues/91).

> It would be a good idea to allow people to select more than one working
> group to join. There's people with useful contributions across topics.
> Effectively this would mean checkboxes rather than radio buttons for the
> question 'Which of our working groups do you want to work with? '

This was indeed confusing. We changed the text to “Which of our working groups do you most want to work with?”, and kept it as single choice. The reasoning is that we want to focus people onto the topic that is their highest priority, since there are only a few weeks to draft commitments. They can in fact join as many groups as they like through the site. This is just a nudge in a more focused direction to help them be as effective as possible.

> I note you've used different language to Peter for the different groups -
> ie Civic Participation rather than Citizen Engagement. Why is that the
> case?

I've just taken the list of working group pages on the site, which were developed in https://github.com/AOGPN/opengovernment.org.au/issues/75

> I find the 'you must agree to these terms' unnecessarily confronting. I'll
> discuss with the Steering Committee & if the Committee is strongly
> committed to the pledge approach, will craft some more inclusive and
> inviting language.

We’ve made it a little warmer with the “We know it’s a bit long, but—”, but otherwise this is based on [the text Peter Timmins suggested](https://github.com/AOGPN/opengovernment.org.au/issues/59#issuecomment-177634835). The wording can definitely be improved to be simpler and less repetitive–I'll open an issue for that.

> When saying Yes it pushes the user to a Submission form. It's an
> unnecessary step from a user experience perspective. Unless there's a
> technical requirement to keep it, can it be dropped, with the prior
> agreement serving as the submission..

Indeed this was a nasty Google Forms limitation–but we've now removed the option to not agree, and it now submits the form without an extra hop. Much nicer :star2:.
