### ISSUE TITLE
ask people basic information about themselves when they sign up

### ISSUE THREAD

**Issue by kat** [AOGPN/opengovernment.org.au#95]
It would be very helpful to know who is part of the network for  a number of reasons, partly to understand who is part of the network what sectors they come from and who they represent. The entry point seems like a good place to capture this. 

the uk site does it but it's immediately useful there because it forms part of their identity on their forum. This is another good reason to use a forum because then everyone has a profile on the site. The google group direction fails to catpture this, but where else would we use the information. How do we display it? For example for organisational members we may want to display their org's information/logo as supporters on the site. I wouldn't want to go back later and have to ask people for this again in the coming days/couple of weeks, that would feel more burdensome.

@equivalentideas raised that we don't want to capture information unnecessarily or raise the barrier to signup any higher.

**Comment by kat** [comment]
@equivalentideas I think you did this already by adding those questions to the form - if this is complete can you close?

**Comment by equivalentideas** [comment]
Currently we're asking:
- Your full name
- Your email
- If you are joining as a representative of an organisation, what’s its name?
- Which of our working groups do you most want to work with?
- Which other civil society organisations or community groups do you work with?

So for organisation reps we are getting the name of their organisation. Is there any other information you need for those organisation members @kat ?

> For example for organisational members we may want to display their org's information/logo as supporters on the site. I wouldn't want to go back later and have to ask people for this again in the coming days/couple of weeks, that would feel more burdensome.

We could add question, “is you organisation joining the network?” instead of the “Are you joining on as a rep of an org”, and then have a whole page of questions for them with the name, website url and anything else that you wanna get up front. Unfortunately there's no image upload for logos.

Are you happy with the current questions or is there more information we need? If you gimmi a list of questions to I can add them in :+1:.

**Comment by kat** [comment]
I think that's just fine as it is.

**Comment by equivalentideas** [comment]
Ace :ok_hand:

**Comment by kat** [comment]
:8ball:
